export enum WoordSoort {
  ZNW_VOORNAAM_VROUW,
  ZNW_VOORNAAM_MAN,
  ZNW_NATIONALITEIT,
  ZNW_ROYALTIEFIGUUR,
  ZNW_FANTASIEFIGUUR,
  ZNW_FAMILIELID,
  ZNW_DIER,
  ZNW_LOCATIE,
  ZNW_PERSONAGE,
  ZNW_BEROEP,
  ZNW_VOORWERP,
}
